version: '3.8'
services:
  redis:
    image: "redis:alpine"
  web:
       build: .
       command: python3 manage.py runserver 0.0.0.0:8000
       ports:
           - 8000:8000
  celery:
       build: .
       command : celery -A drf worker -l info
       volumes:
           - .:/code
       depends_on:
           - redis