# Generated by Django 3.2.4 on 2021-07-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excel_generation_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('generated_file', models.CharField(max_length=100)),
            ],
        ),
    ]
