# Generated by Django 3.2.4 on 2021-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_generation_request',
            name='generated_file',
            field=models.CharField(max_length=300),
        ),
    ]
